/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_poo;

/**
 *
 * @author Cesar J. Santacruz
 */
public class GestionAmbas extends javax.swing.JFrame {

	/**
	 * Creates new form GestionAmbas
	 */
	public GestionAmbas() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel2 = new javax.swing.JPanel();
                panelLProcesador = new javax.swing.JPanel();
                rbtnLi7 = new javax.swing.JRadioButton();
                rbtnLi5 = new javax.swing.JRadioButton();
                rbtnLi3 = new javax.swing.JRadioButton();
                panelBateria = new javax.swing.JPanel();
                rbtnBSi = new javax.swing.JRadioButton();
                rbtnBNo = new javax.swing.JRadioButton();
                lblBrillo = new javax.swing.JPanel();
                txtBrillo = new javax.swing.JTextField();
                jPanel1 = new javax.swing.JPanel();
                panelEProcesador = new javax.swing.JPanel();
                rbtnEi7 = new javax.swing.JRadioButton();
                rbtnEi5 = new javax.swing.JRadioButton();
                rbtnEi3 = new javax.swing.JRadioButton();
                panelVentilacion = new javax.swing.JPanel();
                rbtnVentilador = new javax.swing.JRadioButton();
                rbtnLiquida = new javax.swing.JRadioButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Laptop"));

                panelLProcesador.setBorder(javax.swing.BorderFactory.createTitledBorder("Procesador"));
                panelLProcesador.setEnabled(false);

                rbtnLi7.setText("i7");
                rbtnLi7.setEnabled(false);

                rbtnLi5.setText("i5");
                rbtnLi5.setEnabled(false);

                rbtnLi3.setText("i3");
                rbtnLi3.setEnabled(false);

                javax.swing.GroupLayout panelLProcesadorLayout = new javax.swing.GroupLayout(panelLProcesador);
                panelLProcesador.setLayout(panelLProcesadorLayout);
                panelLProcesadorLayout.setHorizontalGroup(
                        panelLProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLProcesadorLayout.createSequentialGroup()
                                .addGroup(panelLProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbtnLi7)
                                        .addComponent(rbtnLi5)
                                        .addComponent(rbtnLi3))
                                .addGap(0, 40, Short.MAX_VALUE))
                );
                panelLProcesadorLayout.setVerticalGroup(
                        panelLProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLProcesadorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rbtnLi7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnLi5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnLi3)
                                .addContainerGap(22, Short.MAX_VALUE))
                );

                panelBateria.setBorder(javax.swing.BorderFactory.createTitledBorder("Bateria extraible"));
                panelBateria.setEnabled(false);

                rbtnBSi.setText("Si");
                rbtnBSi.setEnabled(false);

                rbtnBNo.setText("No");
                rbtnBNo.setToolTipText("");
                rbtnBNo.setEnabled(false);

                javax.swing.GroupLayout panelBateriaLayout = new javax.swing.GroupLayout(panelBateria);
                panelBateria.setLayout(panelBateriaLayout);
                panelBateriaLayout.setHorizontalGroup(
                        panelBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBateriaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbtnBSi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rbtnBNo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(21, Short.MAX_VALUE))
                );
                panelBateriaLayout.setVerticalGroup(
                        panelBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBateriaLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtnBSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnBNo)
                                .addGap(33, 33, 33))
                );

                lblBrillo.setBorder(javax.swing.BorderFactory.createTitledBorder("Brillo de la pantalla"));
                lblBrillo.setEnabled(false);

                txtBrillo.setEnabled(false);

                javax.swing.GroupLayout lblBrilloLayout = new javax.swing.GroupLayout(lblBrillo);
                lblBrillo.setLayout(lblBrilloLayout);
                lblBrilloLayout.setHorizontalGroup(
                        lblBrilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(lblBrilloLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtBrillo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                lblBrilloLayout.setVerticalGroup(
                        lblBrilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(lblBrilloLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(txtBrillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(panelLProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblBrillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(panelBateria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelLProcesador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblBrillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(15, Short.MAX_VALUE))
                );

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Escritorio"));

                panelEProcesador.setBorder(javax.swing.BorderFactory.createTitledBorder("Procesador"));
                panelEProcesador.setEnabled(false);

                rbtnEi7.setText("i7");
                rbtnEi7.setEnabled(false);

                rbtnEi5.setText("i5");
                rbtnEi5.setEnabled(false);

                rbtnEi3.setText("i3");
                rbtnEi3.setEnabled(false);

                javax.swing.GroupLayout panelEProcesadorLayout = new javax.swing.GroupLayout(panelEProcesador);
                panelEProcesador.setLayout(panelEProcesadorLayout);
                panelEProcesadorLayout.setHorizontalGroup(
                        panelEProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelEProcesadorLayout.createSequentialGroup()
                                .addGroup(panelEProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbtnEi7)
                                        .addComponent(rbtnEi5)
                                        .addComponent(rbtnEi3))
                                .addGap(0, 61, Short.MAX_VALUE))
                );
                panelEProcesadorLayout.setVerticalGroup(
                        panelEProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelEProcesadorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rbtnEi7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnEi5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnEi3)
                                .addContainerGap(22, Short.MAX_VALUE))
                );

                panelVentilacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de ventilacion"));
                panelVentilacion.setEnabled(false);

                rbtnVentilador.setText("Ventilador");
                rbtnVentilador.setEnabled(false);

                rbtnLiquida.setText("Liquida");
                rbtnLiquida.setEnabled(false);

                javax.swing.GroupLayout panelVentilacionLayout = new javax.swing.GroupLayout(panelVentilacion);
                panelVentilacion.setLayout(panelVentilacionLayout);
                panelVentilacionLayout.setHorizontalGroup(
                        panelVentilacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelVentilacionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelVentilacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbtnVentilador)
                                        .addComponent(rbtnLiquida))
                                .addContainerGap(21, Short.MAX_VALUE))
                );
                panelVentilacionLayout.setVerticalGroup(
                        panelVentilacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelVentilacionLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(rbtnVentilador)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnLiquida)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(panelEProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelVentilacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(panelEProcesador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelVentilacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(15, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 437, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addContainerGap()))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 442, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GestionAmbas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GestionAmbas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GestionAmbas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GestionAmbas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GestionAmbas().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel lblBrillo;
        private javax.swing.JPanel panelBateria;
        private javax.swing.JPanel panelEProcesador;
        private javax.swing.JPanel panelLProcesador;
        private javax.swing.JPanel panelVentilacion;
        private javax.swing.JRadioButton rbtnBNo;
        private javax.swing.JRadioButton rbtnBSi;
        private javax.swing.JRadioButton rbtnEi3;
        private javax.swing.JRadioButton rbtnEi5;
        private javax.swing.JRadioButton rbtnEi7;
        private javax.swing.JRadioButton rbtnLi3;
        private javax.swing.JRadioButton rbtnLi5;
        private javax.swing.JRadioButton rbtnLi7;
        private javax.swing.JRadioButton rbtnLiquida;
        private javax.swing.JRadioButton rbtnVentilador;
        private javax.swing.JTextField txtBrillo;
        // End of variables declaration//GEN-END:variables
}

