/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_poo;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Cesar J. Santacruz
 */
public class GestionEscritorio extends javax.swing.JFrame {

	ArrayList<Tiendas> tiendas = new ArrayList<>();
	ArrayList<Producto> productosDeseados = new ArrayList<>();
	String tipoComputador = "Escritorio";
	FondoPanel fondo = new FondoPanel();

	/**
	 * Creates new form GestionEscritorio
	 *
	 * @param tiendas
	 */
	public GestionEscritorio(ArrayList<Tiendas> tiendas) {
		initComponents();
		this.tiendas = tiendas;
		this.setContentPane(fondo);

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btaEProcesador = new javax.swing.ButtonGroup();
                btaDisco = new javax.swing.ButtonGroup();
                btaVentilacion = new javax.swing.ButtonGroup();
                btaCA = new javax.swing.ButtonGroup();
                btaEProcesador1 = new javax.swing.ButtonGroup();
                jPanel1 = new FondoPanel();
                panelEProcesador = new FondoPanel();
                rbtnEi7 = new javax.swing.JRadioButton();
                rbtnEi5 = new javax.swing.JRadioButton();
                rbtnEi3 = new javax.swing.JRadioButton();
                panelVentilacion = new FondoPanel();
                rbtnVentilador = new javax.swing.JRadioButton();
                rbtnLiquida = new javax.swing.JRadioButton();
                panelRam = new FondoPanel();
                cmbRam = new javax.swing.JComboBox<>();
                panelAlmacenamiento = new FondoPanel();
                rbtnHDD = new javax.swing.JRadioButton();
                rbtnSSD = new javax.swing.JRadioButton();
                panelFuente = new FondoPanel();
                cmbFuente = new javax.swing.JComboBox<>();
                panelEProcesador1 = new FondoPanel();
                rbtnE7 = new javax.swing.JRadioButton();
                rbtnE5 = new javax.swing.JRadioButton();
                rbtnE9 = new javax.swing.JRadioButton();
                jPanel2 = new javax.swing.JPanel();
                btnECotizacion = new javax.swing.JButton();
                panelEProvinciaBuscar = new FondoPanel();
                cmbProvincia = new javax.swing.JComboBox<>();
                cbxActivar2 = new javax.swing.JCheckBox();
                panelEPrearmadas = new FondoPanel();
                cmbPrearmadaEscritorio = new javax.swing.JComboBox<>();
                jScrollPane2 = new javax.swing.JScrollPane();
                txaDetallesEscritorio = new javax.swing.JTextArea();
                cbxActivar1 = new javax.swing.JCheckBox();
                btnInicio = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Parts & Bits");
                setIconImage(getIconImage());

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escritorio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(204, 255, 255))); // NOI18N

                panelEProcesador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Procesador Intel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(204, 255, 255))); // NOI18N
                panelEProcesador.setEnabled(false);

                btaEProcesador.add(rbtnEi7);
                rbtnEi7.setForeground(new java.awt.Color(204, 255, 255));
                rbtnEi7.setText("i7");
                rbtnEi7.setEnabled(false);

                btaEProcesador.add(rbtnEi5);
                rbtnEi5.setForeground(new java.awt.Color(204, 255, 255));
                rbtnEi5.setText("i5");
                rbtnEi5.setEnabled(false);

                btaEProcesador.add(rbtnEi3);
                rbtnEi3.setForeground(new java.awt.Color(204, 255, 255));
                rbtnEi3.setText("i3");
                rbtnEi3.setEnabled(false);

                javax.swing.GroupLayout panelEProcesadorLayout = new javax.swing.GroupLayout(panelEProcesador);
                panelEProcesador.setLayout(panelEProcesadorLayout);
                panelEProcesadorLayout.setHorizontalGroup(
                        panelEProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelEProcesadorLayout.createSequentialGroup()
                                .addGroup(panelEProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbtnEi7)
                                        .addComponent(rbtnEi5)
                                        .addComponent(rbtnEi3))
                                .addGap(0, 93, Short.MAX_VALUE))
                );
                panelEProcesadorLayout.setVerticalGroup(
                        panelEProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelEProcesadorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rbtnEi7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnEi5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnEi3)
                                .addContainerGap(39, Short.MAX_VALUE))
                );

                panelVentilacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de ventilacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(204, 255, 255))); // NOI18N
                panelVentilacion.setEnabled(false);

                btaVentilacion.add(rbtnVentilador);
                rbtnVentilador.setForeground(new java.awt.Color(204, 255, 255));
                rbtnVentilador.setText("Ventilador");
                rbtnVentilador.setEnabled(false);

                btaVentilacion.add(rbtnLiquida);
                rbtnLiquida.setForeground(new java.awt.Color(204, 255, 255));
                rbtnLiquida.setText("Liquida");
                rbtnLiquida.setEnabled(false);

                javax.swing.GroupLayout panelVentilacionLayout = new javax.swing.GroupLayout(panelVentilacion);
                panelVentilacion.setLayout(panelVentilacionLayout);
                panelVentilacionLayout.setHorizontalGroup(
                        panelVentilacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelVentilacionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelVentilacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbtnVentilador)
                                        .addComponent(rbtnLiquida))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                panelVentilacionLayout.setVerticalGroup(
                        panelVentilacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelVentilacionLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(rbtnVentilador)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnLiquida)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                panelRam.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Memoria Ram", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(204, 255, 255))); // NOI18N
                panelRam.setEnabled(false);

                cmbRam.setForeground(new java.awt.Color(204, 255, 255));
                cmbRam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "4 GB", "8 GB", "16 GB", "32 GB", "64 GB" }));
                cmbRam.setEnabled(false);

                javax.swing.GroupLayout panelRamLayout = new javax.swing.GroupLayout(panelRam);
                panelRam.setLayout(panelRamLayout);
                panelRamLayout.setHorizontalGroup(
                        panelRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRamLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cmbRam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                panelRamLayout.setVerticalGroup(
                        panelRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRamLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(cmbRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                panelAlmacenamiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de almacenamiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(204, 255, 255))); // NOI18N
                panelAlmacenamiento.setEnabled(false);

                btaDisco.add(rbtnHDD);
                rbtnHDD.setForeground(new java.awt.Color(204, 255, 255));
                rbtnHDD.setText("Disco HDD");
                rbtnHDD.setEnabled(false);

                btaDisco.add(rbtnSSD);
                rbtnSSD.setForeground(new java.awt.Color(204, 255, 255));
                rbtnSSD.setText("Disco SSD");
                rbtnSSD.setEnabled(false);

                javax.swing.GroupLayout panelAlmacenamientoLayout = new javax.swing.GroupLayout(panelAlmacenamiento);
                panelAlmacenamiento.setLayout(panelAlmacenamientoLayout);
                panelAlmacenamientoLayout.setHorizontalGroup(
                        panelAlmacenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelAlmacenamientoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelAlmacenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbtnHDD)
                                        .addComponent(rbtnSSD))
                                .addContainerGap(58, Short.MAX_VALUE))
                );
                panelAlmacenamientoLayout.setVerticalGroup(
                        panelAlmacenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelAlmacenamientoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rbtnHDD)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnSSD)
                                .addContainerGap(44, Short.MAX_VALUE))
                );

                panelFuente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fuente de poder", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(204, 255, 255))); // NOI18N
                panelFuente.setEnabled(false);

                cmbFuente.setForeground(new java.awt.Color(204, 255, 255));
                cmbFuente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "400 W", "500 W", "600 W", "700 W", "800 W", "1000 W" }));
                cmbFuente.setEnabled(false);

                javax.swing.GroupLayout panelFuenteLayout = new javax.swing.GroupLayout(panelFuente);
                panelFuente.setLayout(panelFuenteLayout);
                panelFuenteLayout.setHorizontalGroup(
                        panelFuenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFuenteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cmbFuente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(19, Short.MAX_VALUE))
                );
                panelFuenteLayout.setVerticalGroup(
                        panelFuenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFuenteLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(cmbFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(41, Short.MAX_VALUE))
                );

                panelEProcesador1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Procesador AMD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(204, 255, 255))); // NOI18N
                panelEProcesador1.setForeground(new java.awt.Color(204, 255, 255));
                panelEProcesador1.setEnabled(false);

                btaEProcesador.add(rbtnE7);
                rbtnE7.setForeground(new java.awt.Color(204, 255, 255));
                rbtnE7.setText("Ryzen 7");
                rbtnE7.setEnabled(false);

                btaEProcesador.add(rbtnE5);
                rbtnE5.setForeground(new java.awt.Color(204, 255, 255));
                rbtnE5.setText("Ryzen 5");
                rbtnE5.setEnabled(false);

                btaEProcesador.add(rbtnE9);
                rbtnE9.setForeground(new java.awt.Color(204, 255, 255));
                rbtnE9.setText("Ryzen 9");
                rbtnE9.setEnabled(false);

                javax.swing.GroupLayout panelEProcesador1Layout = new javax.swing.GroupLayout(panelEProcesador1);
                panelEProcesador1.setLayout(panelEProcesador1Layout);
                panelEProcesador1Layout.setHorizontalGroup(
                        panelEProcesador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelEProcesador1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelEProcesador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbtnE7)
                                        .addComponent(rbtnE5)
                                        .addComponent(rbtnE9))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                panelEProcesador1Layout.setVerticalGroup(
                        panelEProcesador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelEProcesador1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rbtnE9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnE7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnE5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(panelEProcesador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(panelFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(panelEProcesador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelRam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(panelAlmacenamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelVentilacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(49, 49, 49))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(panelEProcesador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelEProcesador1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelAlmacenamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(panelFuente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(panelRam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(panelVentilacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(13, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 182, Short.MAX_VALUE)
                );

                btnECotizacion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
                btnECotizacion.setText("Crear Cotizacion");
                btnECotizacion.setPreferredSize(new java.awt.Dimension(165, 40));
                btnECotizacion.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnECotizacionActionPerformed(evt);
                        }
                });

                panelEProvinciaBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROVINCIA QUE DESEA BUSCAR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(204, 255, 255))); // NOI18N

                cmbProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Azuay", "Bolívar", "Cañar", "Chimborazo", "Cotopaxi", "Esmeraldas", "Guayas", "Imbabura", "Loja", "Los Ríos", "Manabí", "Napo", "Pastaza", "Pichincha", "Santo Domingo de los Tsáchilas", "Tungurahua" }));
                cmbProvincia.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                cmbProvinciaItemStateChanged(evt);
                        }
                });

                javax.swing.GroupLayout panelEProvinciaBuscarLayout = new javax.swing.GroupLayout(panelEProvinciaBuscar);
                panelEProvinciaBuscar.setLayout(panelEProvinciaBuscarLayout);
                panelEProvinciaBuscarLayout.setHorizontalGroup(
                        panelEProvinciaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelEProvinciaBuscarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cmbProvincia, 0, 253, Short.MAX_VALUE)
                                .addContainerGap())
                );
                panelEProvinciaBuscarLayout.setVerticalGroup(
                        panelEProvinciaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelEProvinciaBuscarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                cbxActivar2.setForeground(new java.awt.Color(204, 255, 255));
                cbxActivar2.setText("Activar");
                cbxActivar2.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                cbxActivar2ItemStateChanged(evt);
                        }
                });

                panelEPrearmadas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pre-armadas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(204, 255, 255))); // NOI18N
                panelEPrearmadas.setEnabled(false);

                cmbPrearmadaEscritorio.setForeground(new java.awt.Color(204, 255, 255));
                cmbPrearmadaEscritorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
                cmbPrearmadaEscritorio.setEnabled(false);
                cmbPrearmadaEscritorio.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                cmbPrearmadaEscritorioItemStateChanged(evt);
                        }
                });

                jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles"));

                txaDetallesEscritorio.setColumns(20);
                txaDetallesEscritorio.setRows(5);
                txaDetallesEscritorio.setEnabled(false);
                jScrollPane2.setViewportView(txaDetallesEscritorio);

                javax.swing.GroupLayout panelEPrearmadasLayout = new javax.swing.GroupLayout(panelEPrearmadas);
                panelEPrearmadas.setLayout(panelEPrearmadasLayout);
                panelEPrearmadasLayout.setHorizontalGroup(
                        panelEPrearmadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelEPrearmadasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cmbPrearmadaEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                panelEPrearmadasLayout.setVerticalGroup(
                        panelEPrearmadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelEPrearmadasLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEPrearmadasLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cmbPrearmadaEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))
                );

                cbxActivar1.setForeground(new java.awt.Color(204, 255, 255));
                cbxActivar1.setText("Activar");
                cbxActivar1.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                cbxActivar1ItemStateChanged(evt);
                        }
                });

                btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home.png"))); // NOI18N
                btnInicio.setMaximumSize(new java.awt.Dimension(50, 50));
                btnInicio.setMinimumSize(new java.awt.Dimension(50, 50));
                btnInicio.setOpaque(false);
                btnInicio.setPreferredSize(new java.awt.Dimension(50, 50));
                btnInicio.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnInicioActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelEProvinciaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxActivar1)
                                        .addComponent(cbxActivar2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(panelEPrearmadas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(btnECotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(panelEProvinciaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(392, 392, 392))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(cbxActivar1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(panelEPrearmadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbxActivar2)
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnECotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(14, Short.MAX_VALUE))))
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void cmbProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProvinciaItemStateChanged
		// TODO add your handling code here:
		desactivarPartes();

		if (cmbProvincia.getSelectedItem().equals("Seleccionar")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			cmbPrearmadaEscritorio.addItem("Seleccionar");
		} else if (cmbProvincia.getSelectedItem().equals("Azuay")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			// now add back relevant values
			cmbPrearmadaEscritorio.addItem("Seleccionar");
			cmbPrearmadaEscritorio.addItem("HP ALL IN ONE 22-B201LA");
			cmbPrearmadaEscritorio.addItem("CPU GAMER INTEL i3 MAX");
			cmbPrearmadaEscritorio.addItem("CPU GAMER INTEL i7 PLUS");
			cmbPrearmadaEscritorio.addItem("CPU GAMER INTEL i7 MAX");
			cmbPrearmadaEscritorio.addItem("CPU GAMER INTEL i5 MAX");
			cmbPrearmadaEscritorio.addItem("CPU GAMER INTEL i3 PLUS");
			cmbPrearmadaEscritorio.addItem("CPU GAMER INTEL i9 ULTRA CREATORS");
			cmbPrearmadaEscritorio.addItem("CPU GAMER INTEL i9 ULTRA");
		} else if (cmbProvincia.getSelectedItem().equals("Bolívar")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			// now add back relevant values
			cmbPrearmadaEscritorio.addItem("Seleccionar");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C000LA/ AMD A6 A6-9225");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C038LA AMD DUAL");
			cmbPrearmadaEscritorio.addItem("Cpu Xtratech Intel Core I5 DISCO 1TB / 8GB RAM");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO CORE I7, 2TB, 16GB");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL Celeron 8VA, 1TB, 4GB");
			cmbPrearmadaEscritorio.addItem("CPU HP GAMER CORE I9 8VA, RX550 2GB");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL CORE I3 8VA, 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO RYZEN 3 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO AMD A9, 1tb, 4gb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original Core i3 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("All in One HP 24 pulg touch, core i5 8va");
			cmbPrearmadaEscritorio.addItem("CPU Lenovo Core i5 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original AMD A8 PRO 7600, 4gb");
		} else if (cmbProvincia.getSelectedItem().equals("Cañar")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			// now add back relevant values
			cmbPrearmadaEscritorio.addItem("Seleccionar");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C000LA/ AMD A6 A6-9225");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C038LA AMD DUAL");
			cmbPrearmadaEscritorio.addItem("Cpu Xtratech Intel Core I5 DISCO 1TB / 8GB RAM");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO CORE I7, 2TB, 16GB");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL Celeron 8VA, 1TB, 4GB");
			cmbPrearmadaEscritorio.addItem("CPU HP GAMER CORE I9 8VA, RX550 2GB");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL CORE I3 8VA, 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO RYZEN 3 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO AMD A9, 1tb, 4gb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original Core i3 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("All in One HP 24 pulg touch, core i5 8va");
			cmbPrearmadaEscritorio.addItem("CPU Lenovo Core i5 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original AMD A8 PRO 7600, 4gb");
		} else if (cmbProvincia.getSelectedItem().equals("Chimborazo")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			// now add back relevant values
			cmbPrearmadaEscritorio.addItem("Seleccionar");
			cmbPrearmadaEscritorio.addItem("Pc Intel core 2 duo");
		} else if (cmbProvincia.getSelectedItem().equals("Cotopaxi")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			// now add back relevant values
			cmbPrearmadaEscritorio.addItem("Seleccionar");
			cmbPrearmadaEscritorio.addItem("Cpu Computador Gamer Intel Core I7 9na Gen 1tb 16gb Gtx1650");
			cmbPrearmadaEscritorio.addItem("Computador Completo Para Hogar Cyber Oficina Core 2");
			cmbPrearmadaEscritorio.addItem("Pc Cpu Gamer Lenovo Ryzen 7 2tb + 128ssd + 16 Gb + Video 4gb");
			cmbPrearmadaEscritorio.addItem("CPc Gamer I7 I5 I3 Ryzen 5 7 Video Gtx 1660 2060 570");
			cmbPrearmadaEscritorio.addItem("Lenovo Intel Core I5 9na 8 Gb + 1 Tb 4.1ghz");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C000LA/ AMD A6 A6-9225");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C038LA AMD DUAL");
			cmbPrearmadaEscritorio.addItem("Cpu Xtratech Intel Core I5 DISCO 1TB / 8GB RAM");
			cmbPrearmadaEscritorio.addItem("Cpu Intel Core I5 9na Gen 1tb 4gb Led 20 Computadora");
			cmbPrearmadaEscritorio.addItem("Cpu Computadora Intel Core I5 8va Gen 1tb 4gb");
			cmbPrearmadaEscritorio.addItem("Cpu Intel Core I5 8va Gen 1tb 4gb Led 20");
			cmbPrearmadaEscritorio.addItem("Cpu Intel Core I5 8va Gen 1tb 4gb");
		} else if (cmbProvincia.getSelectedItem().equals("Esmeraldas")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			// now add back relevant values
			cmbPrearmadaEscritorio.addItem("Seleccionar");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C000LA/ AMD A6 A6-9225");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C038LA AMD DUAL");
			cmbPrearmadaEscritorio.addItem("Cpu Xtratech Intel Core I5 DISCO 1TB / 8GB RAM");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO CORE I7, 2TB, 16GB");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL Celeron 8VA, 1TB, 4GB");
			cmbPrearmadaEscritorio.addItem("CPU HP GAMER CORE I9 8VA, RX550 2GB");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL CORE I3 8VA, 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO RYZEN 3 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO AMD A9, 1tb, 4gb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original Core i3 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("All in One HP 24 pulg touch, core i5 8va");
			cmbPrearmadaEscritorio.addItem("CPU Lenovo Core i5 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original AMD A8 PRO 7600, 4gb");
		} else if (cmbProvincia.getSelectedItem().equals("Guayas")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			// now add back relevant values
			cmbPrearmadaEscritorio.addItem("Seleccionar");
			cmbPrearmadaEscritorio.addItem("APPLE iMac Intel Core I5");
			cmbPrearmadaEscritorio.addItem("APPLE iMac Intel Core I7");
			cmbPrearmadaEscritorio.addItem("DELL OPTIPLEX 3070");
			cmbPrearmadaEscritorio.addItem("DELL OPTIPLEX 7070");
			cmbPrearmadaEscritorio.addItem("DELL AIO OPTIPLEX 5270");
			cmbPrearmadaEscritorio.addItem("DELL OPTIPLEX 7070 UFF");
			cmbPrearmadaEscritorio.addItem("DELL AIO Inspiron 5490");
			cmbPrearmadaEscritorio.addItem("HP ProDesk 400 G6");
			cmbPrearmadaEscritorio.addItem("HP AIO ProOne 400 G5");
			cmbPrearmadaEscritorio.addItem("HP EliteDesk 800 G4");
			cmbPrearmadaEscritorio.addItem("HP EliteDesk 705 G4");
			cmbPrearmadaEscritorio.addItem("HP ProDesk 400 G6");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C000LA/ AMD A6 A6-9225");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C038LA AMD DUAL");
			cmbPrearmadaEscritorio.addItem("Cpu Xtratech Intel Core I5 DISCO 1TB / 8GB RAM");
			cmbPrearmadaEscritorio.addItem("QUASAD AIO Intel Celeron G4930");
			cmbPrearmadaEscritorio.addItem("QUASAD I7-8700 Z370");
			cmbPrearmadaEscritorio.addItem("QUASAD AIO T24");
			cmbPrearmadaEscritorio.addItem("Dell Optiplex 7060");
			cmbPrearmadaEscritorio.addItem("Dell Optiplex 3060");
			cmbPrearmadaEscritorio.addItem("Dell Optiplex 3060 SFF");
			cmbPrearmadaEscritorio.addItem("PBA Torre");
		} else if (cmbProvincia.getSelectedItem().equals("Imbabura")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			// now add back relevant values
			cmbPrearmadaEscritorio.addItem("Seleccionar");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C000LA/ AMD A6 A6-9225");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C038LA AMD DUAL");
			cmbPrearmadaEscritorio.addItem("Cpu Xtratech Intel Core I5 DISCO 1TB / 8GB RAM");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO CORE I7, 2TB, 16GB");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL Celeron 8VA, 1TB, 4GB");
			cmbPrearmadaEscritorio.addItem("CPU HP GAMER CORE I9 8VA, RX550 2GB");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL CORE I3 8VA, 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO RYZEN 3 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO AMD A9, 1tb, 4gb");
			cmbPrearmadaEscritorio.addItem("Cpu Intel Core I5 8va Gen 1tb 4gb Led 20");
			cmbPrearmadaEscritorio.addItem("Cpu Intel Core I5 8va Gen 1tb 4gb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original Core i3 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("All in One HP 24 pulg touch, core i5 8va");
			cmbPrearmadaEscritorio.addItem("CPU Lenovo Core i5 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original AMD A8 PRO 7600, 4gb");
		} else if (cmbProvincia.getSelectedItem().equals("Loja")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			// now add back relevant values
			cmbPrearmadaEscritorio.addItem("Seleccionar");
			cmbPrearmadaEscritorio.addItem("HP EliteDesk 705 G4 AMD Ryzen 5 Pro 2400g 8GB 1TB DW W10-Pro");
			cmbPrearmadaEscritorio.addItem("HP EliteDesk 800 G4 I7-8700 8GB 1TB DW SFF W10-PRO Black");
			cmbPrearmadaEscritorio.addItem("DELL OPTIPLEX 7070 UFF I7-8565 16GB 256GB-M.2 W10-PRO Black");
			cmbPrearmadaEscritorio.addItem("DELL OPTIPLEX 7070 I7-9700 8GB 1TB DVD WIN10-PRO SFF BLACK");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C000LA/ AMD A6 A6-9225");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C038LA AMD DUAL");
			cmbPrearmadaEscritorio.addItem("Cpu Xtratech Intel Core I5 DISCO 1TB / 8GB RAM");
			cmbPrearmadaEscritorio.addItem("DELL OPTIPLEX 3070 I5-9700 4GB 1TB 1W10-PRO SFF BLACK – MONITOR E2020H");
			cmbPrearmadaEscritorio.addItem("APPLE iMac Intel Core I5 8GB 512GB-SSD 27Inc 5K Retina 4USB3.0 OS Silver");
			cmbPrearmadaEscritorio.addItem("APPLE iMac Intel Core I5 8GB 256GB-SSD 27Inc 5K Retina 4USB3.0 OS Silve");
			cmbPrearmadaEscritorio.addItem("APPLE iMac Intel Core I5 8GB 1TB 27Inc 5K Retina 4USB3.0 OS Silver");
			cmbPrearmadaEscritorio.addItem("COMPUTADOR CPU XTRATECH INTEL GOLD UBUNTU");
			cmbPrearmadaEscritorio.addItem("COMPUTADOR CPU XTRATECH INTEL i3 UBUNTU");
			cmbPrearmadaEscritorio.addItem("COMPUTADOR CPU XTRATECH INTEL AMD UBUNTU");
		} else if (cmbProvincia.getSelectedItem().equals("Los Ríos")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			// now add back relevant values
			cmbPrearmadaEscritorio.addItem("Seleccionar");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C000LA/ AMD A6 A6-9225");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C038LA AMD DUAL");
			cmbPrearmadaEscritorio.addItem("Cpu Xtratech Intel Core I5 DISCO 1TB / 8GB RAM");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO CORE I7, 2TB, 16GB");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL Celeron 8VA, 1TB, 4GB");
			cmbPrearmadaEscritorio.addItem("CPU HP GAMER CORE I9 8VA, RX550 2GB");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL CORE I3 8VA, 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO RYZEN 3 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("Cpu Intel Core I5 8va Gen 1tb 4gb Led 20");
			cmbPrearmadaEscritorio.addItem("Cpu Intel Core I5 8va Gen 1tb 4gb");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO AMD A9, 1tb, 4gb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original Core i3 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("All in One HP 24 pulg touch, core i5 8va");
			cmbPrearmadaEscritorio.addItem("CPU Lenovo Core i5 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original AMD A8 PRO 7600, 4gb");
		} else if (cmbProvincia.getSelectedItem().equals("Manabí")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			// now add back relevant values
			cmbPrearmadaEscritorio.addItem("Seleccionar");
			cmbPrearmadaEscritorio.addItem("Computadora de escritorio Intel Celeron");
			cmbPrearmadaEscritorio.addItem("Computadora de escritorio Intel i5");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C000LA/ AMD A6 A6-9225");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C038LA AMD DUAL");
			cmbPrearmadaEscritorio.addItem("Cpu Xtratech Intel Core I5 DISCO 1TB / 8GB RAM");
			cmbPrearmadaEscritorio.addItem("Computadora de escritorio XTRATECH");
			cmbPrearmadaEscritorio.addItem("Computadora de escritorio AMD Athlon");
		} else if (cmbProvincia.getSelectedItem().equals("Napo")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			// now add back relevant values
			cmbPrearmadaEscritorio.addItem("Seleccionar");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C000LA/ AMD A6 A6-9225");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C038LA AMD DUAL");
			cmbPrearmadaEscritorio.addItem("Cpu Xtratech Intel Core I5 DISCO 1TB / 8GB RAM");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO CORE I7, 2TB, 16GB");
			cmbPrearmadaEscritorio.addItem("Cpu Intel Core I5 8va Gen 1tb 4gb Led 20");
			cmbPrearmadaEscritorio.addItem("Cpu Intel Core I5 8va Gen 1tb 4gb");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL Celeron 8VA, 1TB, 4GB");
			cmbPrearmadaEscritorio.addItem("CPU HP GAMER CORE I9 8VA, RX550 2GB");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL CORE I3 8VA, 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO RYZEN 3 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO AMD A9, 1tb, 4gb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original Core i3 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("All in One HP 24 pulg touch, core i5 8va");
			cmbPrearmadaEscritorio.addItem("CPU Lenovo Core i5 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original AMD A8 PRO 7600, 4gb");
		} else if (cmbProvincia.getSelectedItem().equals("Pastaza")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			// now add back relevant values
			cmbPrearmadaEscritorio.addItem("Seleccionar");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C000LA/ AMD A6 A6-9225");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C038LA AMD DUAL");
			cmbPrearmadaEscritorio.addItem("Cpu Xtratech Intel Core I5 DISCO 1TB / 8GB RAM");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO CORE I7, 2TB, 16GB");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL Celeron 8VA, 1TB, 4GB");
			cmbPrearmadaEscritorio.addItem("CPU HP GAMER CORE I9 8VA, RX550 2GB");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL CORE I3 8VA, 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO RYZEN 3 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO AMD A9, 1tb, 4gb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original Core i3 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("All in One HP 24 pulg touch, core i5 8va");
			cmbPrearmadaEscritorio.addItem("CPU Lenovo Core i5 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("Cpu Intel Core I5 8va Gen 1tb 4gb Led 20");
			cmbPrearmadaEscritorio.addItem("Cpu Intel Core I5 8va Gen 1tb 4gb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original AMD A8 PRO 7600, 4gb");
		} else if (cmbProvincia.getSelectedItem().equals("Pichincha")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			// now add back relevant values
			cmbPrearmadaEscritorio.addItem("Seleccionar");
			cmbPrearmadaEscritorio.addItem("HOGAR CI3-8");
			cmbPrearmadaEscritorio.addItem("SEMIPROFESIONAL CI5-8");
			cmbPrearmadaEscritorio.addItem("PROFESIONAL CI7-16");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C000LA/ AMD A6 A6-9225");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C038LA AMD DUAL");
			cmbPrearmadaEscritorio.addItem("Cpu Xtratech Intel Core I5 DISCO 1TB / 8GB RAM");
			cmbPrearmadaEscritorio.addItem("COMPUTADOR ARMADO I3");
			cmbPrearmadaEscritorio.addItem("COMPUTADOR ARMADO I7");
			cmbPrearmadaEscritorio.addItem("COMPUTADOR ARMADO I3-8VA GEN");

		} else if (cmbProvincia.getSelectedItem().equals("Santo Domingo de los Tsáchilas")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			// now add back relevant values
			cmbPrearmadaEscritorio.addItem("Seleccionar");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C000LA/ AMD A6 A6-9225");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C038LA AMD DUAL");
			cmbPrearmadaEscritorio.addItem("Cpu Xtratech Intel Core I5 DISCO 1TB / 8GB RAM");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO CORE I7, 2TB, 16GB");
			cmbPrearmadaEscritorio.addItem("COMPUTADOR CPU XTRATECH INTEL GOLD UBUNTU");
			cmbPrearmadaEscritorio.addItem("COMPUTADOR CPU XTRATECH INTEL i3 UBUNTU");
			cmbPrearmadaEscritorio.addItem("COMPUTADOR CPU XTRATECH INTEL AMD UBUNTU");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL Celeron 8VA, 1TB, 4GB");
			cmbPrearmadaEscritorio.addItem("CPU HP GAMER CORE I9 8VA, RX550 2GB");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL CORE I3 8VA, 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO RYZEN 3 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO AMD A9, 1tb, 4gb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original Core i3 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("All in One HP 24 pulg touch, core i5 8va");
			cmbPrearmadaEscritorio.addItem("CPU Lenovo Core i5 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("Cpu Intel Core I5 8va Gen 1tb 4gb Led 20");
			cmbPrearmadaEscritorio.addItem("Cpu Intel Core I5 8va Gen 1tb 4gb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original AMD A8 PRO 7600, 4gb");
		} else if (cmbProvincia.getSelectedItem().equals("Tungurahua")) {
			// we know that the user picked "Course 1", now change box2 to match
			// first clear everything
			cmbPrearmadaEscritorio.removeAllItems();
			// now add back relevant values
			cmbPrearmadaEscritorio.addItem("Seleccionar");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C000LA/ AMD A6 A6-9225");
			cmbPrearmadaEscritorio.addItem("Hp AIO 22-C038LA AMD DUAL");
			cmbPrearmadaEscritorio.addItem("Cpu Xtratech Intel Core I5 DISCO 1TB / 8GB RAM");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO CORE I7, 2TB, 16GB");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL Celeron 8VA, 1TB, 4GB");
			cmbPrearmadaEscritorio.addItem("CPU HP GAMER CORE I9 8VA, RX550 2GB");
			cmbPrearmadaEscritorio.addItem("CPU HP ORIGINAL CORE I3 8VA, 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO RYZEN 3 1TB, 8GB");
			cmbPrearmadaEscritorio.addItem("CPU LENOVO AMD A9, 1tb, 4gb");
			cmbPrearmadaEscritorio.addItem("CPU HP Original Core i3 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("All in One HP 24 pulg touch, core i5 8va");
			cmbPrearmadaEscritorio.addItem("CPU Lenovo Core i5 9na, 1tb");
			cmbPrearmadaEscritorio.addItem("COMPUTADOR CPU XTRATECH INTEL GOLD UBUNTU");
			cmbPrearmadaEscritorio.addItem("COMPUTADOR CPU XTRATECH INTEL i3 UBUNTU");
			cmbPrearmadaEscritorio.addItem("COMPUTADOR CPU XTRATECH INTEL AMD UBUNTU");
			cmbPrearmadaEscritorio.addItem("CPU HP Original AMD A8 PRO 7600, 4gb");
		} else {
			// ...
		}
        }//GEN-LAST:event_cmbProvinciaItemStateChanged

        private void cmbPrearmadaEscritorioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPrearmadaEscritorioItemStateChanged
		// TODO add your handling code here:

		if (cmbPrearmadaEscritorio.getSelectedItem() == null) {
			txaDetallesEscritorio.setText("");
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Seleccionar")) {
			txaDetallesEscritorio.setText("");
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("HOGAR CI3-8")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("PcLaptop", "PC HOGAR", "INTEL CORE I3",
					"1 TB", "8 RAM DDR4", "Webcam + Micrófono",
					"No Aplica", "20Inc", "DVD WRITER", "INTEL GRAPHICS",
					"WINDOWS 10 ORIGINAL", "USB 3.0 x 3", "629.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("SEMIPROFESIONAL CI5-8")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("PcLaptop", "PC SEMIPROFESIONAL", "INTEL CORE I5",
					"2 TB", "8 RAM DDR4", "Webcam + Micrófono",
					"No Aplica", "20Inc", "DVD WRITER", "INTEL GRAPHICS",
					"WINDOWS 10 ORIGINAL", "USB 3.0 x 3", "749.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("PROFESIONAL CI7-16")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("PcLaptop", "PC PROFESIONAL", "INTEL CORE I7",
					"2 TB", "16 RAM DDR4", "Webcam + Micrófono",
					"No Aplica", "20Inc", "DVD WRITER", "4 GB DEDICADO PCI XPRESS",
					"WINDOWS 10 ORIGINAL", "USB 3.0 x 3", "1,099.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("COMPUTADOR ARMADO I3")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("PcShop", "PCSHOP", "Intel Core I3-9100 - 3.6ghz",
					"WD 1tb 7200rpm", "Kingston 8gb Ddr4 Pc-2400", "No Incluye",
					"No Aplica", "LG 19.5", "DVD WRITER", "INTEL GRAPHICS",
					"WINDOWS 10 ORIGINAL", "USB 3.0 x 3", "560.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("COMPUTADOR ARMADO I7")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("PcShop", "PCSHOP", "Intel Core I7-9700 - 3.0ghz",
					"WD 1tb 7200rpm", "Kingston 8gb Ddr4 Pc-2400", "No Incluye",
					"No Aplica", "LG 19.5", "DVD WRITER", "INTEL GRAPHICS",
					"WINDOWS 10 ORIGINAL", "USB 3.0 x 3", "899.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("COMPUTADOR ARMADO I3-8VA GEN")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("PcShop", "PCSHOP", "Intel Core I3-8100 - 3.6ghz",
					"WD 1tb 7200rpm", "Adata 4gb Pc-2400 Ddr4", "No Incluye",
					"No Aplica", "HP 18.5", "DVD WRITER", "INTEL GRAPHICS",
					"WINDOWS 10 ORIGINAL", "USB 3.0 x 3", "516.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("APPLE iMac Intel Core I5")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Tecnomega Storep", "Apple", "Intel Core I5",
					"512GB-SSD", "8GB", "Si",
					"No Aplica", "27Inc 5K Retina", "DVD WRITER", "INTEL GRAPHICS",
					"Mac OS", "USB 3.0 x 4", "2,726.67"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("APPLE iMac Intel Core I7")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Tecnomega Storep", "Apple", "Intel Core I7",
					"512GB-SSD", "8GB", "Si",
					"No Aplica", "27Inc 5K Retina", "DVD WRITER", "INTEL GRAPHICS",
					"Mac OS", "USB 3.0 x 4", "3,128.89"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("DELL OPTIPLEX 3070")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Tecnomega Storep", "Dell", "Intel Core I5-9700",
					"512GB-SSD", "4GB", "Si",
					"No Aplica", "MONITOR E2020H 20.5", "DVD WRITER", "INTEL GRAPHICS",
					" WIndows 10 PRO", "USB 3.0 x 6", "886.67"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("DELL OPTIPLEX 7070")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Tecnomega Storep", "Dell", "Intel Core I7-8565",
					"256GB-M.2", "16GB", "Si",
					"No Aplica", "MONITOR E2020H 20.5", "DVD WRITER", "INTEL GRAPHICS",
					" WIndows 10 PRO", "USB 3.0 x 6", "1,272.22"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("DELL AIO OPTIPLEX 5270")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Tecnomega Storep", "Dell", "Intel Core I5-9500",
					"256GB-M.2", "8GB", "No Incluye",
					"No Aplica", "DELL 20.5", "DVD WRITER", "INTEL GRAPHICS",
					" WIndows 10 PRO", "USB 3.0 x 5", "1,041.11"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("DELL OPTIPLEX 7070 UFF")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Tecnomega Storep", "Dell", "Intel Core I5-8250",
					"256GB-SDD", "8GB", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					" WIndows 10 PRO", "USB 3.0 x 6", "994.44"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("DELL AIO Inspiron 5490")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Tecnomega Storep", "Dell", "Intel Core I5-10210U",
					"1TB HDD", "12GB", "Si",
					"No Aplica", "23.8 TOUCH", "DVD WRITER", "INTEL GRAPHICS",
					" WIndows 10 PRO", "USB 3.0 x 3", "1,133.33"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("HP ProDesk 400 G6")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Tecnomega Storep", "HP", "Intel Core I7-9700",
					"1TB HDD", "8GB", "Si",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					" WIndows 10 PRO", "USB 3.0 x 3", "716.67"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("HP AIO ProOne 400 G5")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Tecnomega Storep", "HP", "Intel Core I7-9700",
					"1TB HDD", "8GB", "Si",
					"No Aplica", "23.8Inc", "DVD WRITER", "INTEL GRAPHICS",
					" WIndows 10 PRO", "USB 3.1 x 2", "887.78"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("HP EliteDesk 800 G4")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Tecnomega Storep", "HP", "Intel Core I7-8700",
					"1TB HDD", "8GB", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					" WIndows 10 PRO", "USB 3.1 x 5", "1,165.56"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("HP EliteDesk 705 G4")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Tecnomega Storep", "HP", "AMD Ryzen 5 Pro 2400g",
					"1TB HDD", "8GB", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "Radeon",
					" WIndows 10 PRO", "USB 3.1 x 5", "1,082.22"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("HP ProDesk 400 G6")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Tecnomega Storep", "HP", "Intel Core I7-9700",
					"1TB HDD", "8GB", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					" WIndows 10 PRO", "USB 3.0 x 2", "964.44"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("QUASAD AIO Intel Celeron G4930")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Tecnomega Storep", "QUASAD", "Intel Celeron G4930",
					"256GB-SSD", "8GB", "Si",
					"No Aplica", "23.8Inc", "DVD WRITER", "INTEL GRAPHICS",
					" WIndows 10 PRO", "USB 3.0 x 3", "480.21"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("QUASAD I7-8700 Z370")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Tecnomega Storep", "QUASAD", "Intel Core I7-8700",
					"1TB", "8GB", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					" WIndows 10 PRO", "USB 3.0 x 6", "929.74"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("QUASAD AIO T24")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Tecnomega Storep", "QUASAD", "Intel Core I7-7700",
					"240GB SSD", "8GB", "Si",
					"No Aplica", "23.8Inc", "DVD WRITER", "INTEL GRAPHICS",
					" WIndows 10 PRO", "USB 3.0 x 3", "1,073.19"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Dell Optiplex 7060")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("TecnoSmart", "Dell", "Intel Core i5 8500",
					"1TB HDD", "8GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					" WIndows 10 PRO", "USB 3.0 x 4", "1,094.99"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Dell Optiplex 3060")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("TecnoSmart", "Dell", "Intel Core i5 8400",
					"1TB HDD", "4GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					" WIndows 10 PRO", "USB 3.0 x 4", "889.99"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Dell Optiplex 3060 SFF")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("TecnoSmart", "Dell", "Intel Core i5 8400",
					"500GB SSD", "8GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					" WIndows 10 PRO", "USB 3.0 x 4", "964.99"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("PBA Torre")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("TecnoSmart", "Dell", "AMD Ryzen 7 3700x",
					"1TB HDD", "16GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "GTX 1650 SUPER 4GB",
					" WIndows 10 PRO", "USB 3.1 x 6", "1,264.99"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("HP ALL IN ONE 22-B201LA")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Computadoras De Venta", "Hp", "AMD Quad-Core A6-7310",
					"1TB HDD", "4 GB de DRAM DDR3", "No Incluye",
					"No Aplica", "21,5Inc", "DVD WRITER", "Radeon™ R4",
					" WIndows 10", "USB 3.1 x 2", "580.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPU GAMER INTEL i3 MAX")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("CompuPlucEC", "New Era", "Intel Core i3 9100F",
					"1TB HDD", "8 GB de DRAM DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "GTX 1030 2GB",
					" WIndows 10", "USB 3.1 x 4", "700.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPU GAMER INTEL i7 PLUS")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("CompuPlucEC", "New Era", "Intel Core i7 10700",
					"2TB HDD + 128GB SSD", "16 GB de DRAM DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "GTX 1660 SUPER 6GB",
					" WIndows 10", "USB 3.1 x 6", "1600.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPU GAMER INTEL i7 MAX")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("CompuPlucEC", "New Era", "Intel Core i3 9700F",
					"1TB HDD + 128GB SSD", "16 GB de DRAM DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "GTX 1650 SUPER 4GB",
					" WIndows 10", "USB 3.1 x 4", "1300.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPU GAMER INTEL i5 MAX")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("CompuPlucEC", "New Era", "Intel Core i5 9400F",
					"480GB SSD", "8 GB de DRAM DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "GTX 1650 SUPER 4GB",
					" WIndows 10", "USB 3.1 x 4", "900.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPU GAMER INTEL i3 PLUS")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("CompuPlucEC", "New Era", "Intel Core i3 10100",
					"1TB HDD + 240GB SSD", "8 GB de DRAM DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "GTX 1030 2GB",
					" WIndows 10", "USB 3.1 x 4", "800.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPU GAMER INTEL i9 ULTRA CREATORS")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("CompuPlucEC", "New Era", "Intel Core i9 9900k",
					"2TB HDD + 128GB SSD M.2", "32 GB de DRAM DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "RTX 2070 SUPER 8GB",
					" WIndows 10 PRO", "USB 3.1 x 6", "3000.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPU GAMER INTEL i9 ULTRA")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("CompuPlucEC", "New Era", "Intel Core i9 9900k",
					"2TB HDD + 128GB SSD M.2", "16 GB de DRAM DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "RTX 2060 SUPER 8GB",
					" WIndows 10 PRO", "USB 3.1 x 6", "2500.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Pc Intel core 2 duo")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("SERVICOMPU", "Dell", "Intel core 2 duo",
					"64GB HDD", "2 GB de DRAM DDR2", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					" WIndows 8.1", "USB 2.0 x 3", "249.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Computador Completo Para Hogar Cyber Oficina Core 2")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("PUERTO LIBRE", "Dell", "Intel core 2 duo 3.0ghz",
					"160GB HDD", "2 GB de DRAM DDR2", "No Incluye",
					"No Aplica", "15Inc", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 Home", "USB 2.0 x 3", "130.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Pc Cpu Gamer Lenovo Ryzen 7 2tb + 128ssd + 16 Gb + Video 4gb")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("PUERTO LIBRE", "LENOVO", "AMD Ryzen 7 2700",
					"2TB HDD", "16 GB de DRAM DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "AMD Radeon ™ RX 560 4GB",
					"Windows 10 Home", "USB 3.0 x 3", "979.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPc Gamer I7 I5 I3 Ryzen 5 7 Video Gtx 1660 2060 570")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("DIGITAL", "Sin Marca", "AMD Ryzen 3 2300",
					"1TB HDD", "4 GB de DRAM DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "Graficos Integrados",
					"Windows 10 Home", "USB 3.0 x 3", "429.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Lenovo Intel Core I5 9na 8 Gb + 1 Tb 4.1ghz")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("PUERTO LIBRE", "Sin Marca", "Intel Core i5-9400 2.90GHz, hasta 4.10GHz con Turbo Boost, 6 núcleo, 9 MB Cache",
					"1 TB HDD 7200 RPM", "8 GB DDR4 2666 MHz", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "Gráficos integrados Intel UHD 630",
					"Windows 10 Home", "4 x USB 3.1 (frontal)\n"
					+ "1 x USB 3.1 Tipo-C Gen 1 (frontal)\n"
					+ "4 x USB 2.0 (trasero)\n"
					+ "1 x VGA\n"
					+ "1 x salida HDMI\n"
					+ "1 x Gigabit Ethernet 10/100/1000 LAN\n"
					+ "7-1 lector de tarjetas multimedia\n"
					+ "2 x conector de micrófono (1 posterior / 1 frontal)\n"
					+ "2 x auriculares", "679.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Cpu Intel Core I5 9na Gen 1tb 4gb Led 20 Computadora")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Gold Buyer", "Sin Marca", "Intel Core i5-9400 2.90GHz",
					"1 TB HDD 7200 RPM", "4 GB DDR4", "No Incluye",
					"No Aplica", "LED LG de 20Inc", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 Home", "8 x USB 3.1 (frontal)\n"
					+ "1 x salida HDMI\n"
					+ "1 x Gigabit Ethernet 10/100/1000 LAN\n"
					+ "7-1 lector de tarjetas multimedia\n"
					+ "2 x conector de micrófono (1 posterior / 1 frontal)\n"
					+ "2 x auriculares", "525.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Cpu Computadora Intel Core I5 8va Gen 1tb 4gb")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Gold Buyer", "Sin Marca", "Intel Core I5-8400 8va",
					"1 TB HDD 7200 RPM", "4 GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 Home", "6 Puertos USB\n"
					+ "Teclado USB\n"
					+ "Mouse USB", "385.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Cpu Intel Core I5 8va Gen 1tb 4gb Led 20")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Gold Buyer", "Sin Marca", "Intel Core I5-8400 8va",
					"1 TB HDD 7200 RPM", "4 GB DDR4", "No Incluye",
					"No Aplica", "LED LG de 20Inc", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 Home", "7 Puertos USB\n"
					+ "Teclado USB\n"
					+ "Mouse USB", "475.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Cpu Intel Core I5 8va Gen 1tb 4gb Led 20")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Gold Buyer", "Sin Marca", "Intel Core I5-8400 8va",
					"1 TB HDD 7200 RPM", "4 GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 Home", "7 Puertos USB\n"
					+ "Teclado USB\n"
					+ "Mouse USB", "375.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("HP EliteDesk 705 G4 AMD Ryzen 5 Pro 2400g 8GB 1TB DW W10-Pro")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Toners", "HP", "AMD Ryzen 5 Pro 2400g",
					"1 TB HDD 7200 RPM", "8GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "Radeon",
					"Windows 10 Home", "No especifica informacion", "1,198.02"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("HP EliteDesk 800 G4 I7-8700 8GB 1TB DW SFF W10-PRO Black")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Toners", "HP", "Intel Core I7-8700",
					"1 TB HDD 7200 RPM", "8GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 Home", "USB 3.0 x 4", "1,342.72"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("DELL OPTIPLEX 7070 UFF I7-8565 16GB 256GB-M.2 W10-PRO Black")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Toners", "DELL", "Intel Core I7-8565",
					"1 TB HDD 7200 RPM + 256GB-M.2", "16GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 PRO", "USB 3.0 x 5", "1,408.35"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("DELL OPTIPLEX 7070 I7-9700 8GB 1TB DVD WIN10-PRO SFF BLACK")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Toners", "DELL", "Intel Core I7-9700",
					"1 TB HDD 7200 RPM", "8GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 PRO", "USB 3.0 x 5", "1,227.52"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("DELL OPTIPLEX 3070 I5-9700 4GB 1TB 1W10-PRO SFF BLACK – MONITOR E2020H")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Toners", "DELL", "Intel Core I5-9500",
					"1 TB HDD 7200 RPM", "4GB DDR4", "No Incluye",
					"No Aplica", "MONITOR E2020H", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 PRO", "USB 3.0 x 5", "1,021.44"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("APPLE iMac Intel Core I5 8GB 512GB-SSD 27Inc 5K Retina 4USB3.0 OS Silver")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Toners", "APPLE", "Intel Core I5-9500",
					"512GB SSD", "8GB DDR4", "Si",
					"No Aplica", "27Inc 5K Retina", "DVD WRITER", "INTEL GRAPHICS",
					"MacOS", "4USB3.0", "3,141.12"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("APPLE iMac Intel Core I5 8GB 256GB-SSD 27Inc 5K Retina 4USB3.0 OS Silver")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Toners", "APPLE", "Intel Core I5-9500",
					"256GB SSD", "8GB DDR4", "Si",
					"No Aplica", "27Inc 5K Retina", "DVD WRITER", "INTEL GRAPHICS",
					"MacOS", "4USB3.0", "2,705.92"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("APPLE iMac Intel Core I5 8GB 1TB 27Inc 5K Retina 4USB3.0 OS Silver")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Toners", "APPLE", "Intel Core I5-9500",
					"1TB HDD", "8GB DDR4", "Si",
					"No Aplica", "27Inc 5K Retina", "DVD WRITER", "INTEL GRAPHICS",
					"MacOS", "4USB3.0", "2,540.80"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("COMPUTADOR CPU XTRATECH INTEL GOLD UBUNTU")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Toners", "XTRATECH", "Intel Pentium Gold",
					"1TB HDD", "4GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					"Ubuntu", "USB3.0 x 3", "358.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("COMPUTADOR CPU XTRATECH INTEL i3 UBUNTU")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Toners", "XTRATECH", "INTEL CORE I3-9100F 3.6GHZ",
					"1TB HDD", "8GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "ASUS 1GB",
					"Ubuntu", "USB3.0 x 3", "358.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("COMPUTADOR CPU XTRATECH INTEL AMD UBUNTU")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Toners", "XTRATECH", "AMD E1-6010 DUAL-CORE",
					"1TB HDD", "8GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "Radeon Graphics",
					"Ubuntu", "USB3.1 x 3", "358.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Computadora de escritorio Intel Celeron")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Compulaser", "Sin Marca", "Intel Celeron Core i3 de 9na Generación",
					"1TB HDD", "8GB DDR4", "No Incluye",
					"No Aplica", "20Inc", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10", "USB3.1 x 3 \n Teclado \n Mouse", "749.99"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Computadora de escritorio Intel i5")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Compulaser", "Sin Marca", "Intel Core i5 de 9na Generación",
					"1TB HDD", "8GB DDR4", "Si",
					"No Aplica", "20Inc", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10", "USB3.1 x 3 \n Teclado \n Mouse", "824.99"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Computadora de escritorio XTRATECH")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Compulaser", "Sin Marca", "AMD Athlon 3000G 3.5 Ghz",
					"1TB HDD", "4GB DDR4", "Si",
					"No Aplica", "20Inc", "DVD WRITER", "Radeon",
					"Windows 10", "USB3.1 x 3 \n Teclado \n Mouse", "516.99"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Computadora de escritorio AMD Athlon")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Compulaser", "Sin Marca", "AMD Athlon 3000G 3.5 Ghz",
					"1TB HDD", "4GB DDR4", "Si",
					"No Aplica", "20Inc", "DVD WRITER ", "Radeon",
					"Windows 10", "USB3.1 x 3 \n Teclado \n Mouse", "690.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Hp AIO 22-C000LA/ AMD A6 A6-9225")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("BestPC", "HP", "AMD A6-9225",
					"1TB HDD", "4GB DDR4", "Si",
					"No Aplica", "21,5Inc LED", "DVD WRITER", "Radeon",
					"Windows 10 Home", "USB3.1 x 3", "650.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Hp AIO 22-C038LA AMD DUAL")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("BestPC", "HP", "AMD A6-9225",
					"1TB HDD + 256 GB SSD", "4GB DDR4", "Si",
					"No Aplica", "21,5Inc LED", "DVD WRITER", "Radeon",
					"Windows 10 Home", "USB3.0 x 3", "717,76"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("Cpu Xtratech Intel Core I5 DISCO 1TB / 8GB RAM")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("BestPC", "Xtratech", "INTEL CORE I5-7400 TO 3.5GHZ",
					"1TB HDD", "8GB DDR4", "Si",
					"No Aplica", "21,5Inc LED", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 Home", "USB3.0 x 6", "642.94"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPU LENOVO CORE I7, 2TB, 16GB")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Novicompu", "Lenovo", "INTEL CORE i7 8700k",
					"2TB HDD", "16GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 Home", "USB3.0 x 6", "895.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPU HP ORIGINAL Celeron 8VA, 1TB, 4GB")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Novicompu", "HP", "Intel Celeron 8va",
					"1TB HDD", "4GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 Home", "USB3.0 x 6", "459.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPU HP GAMER CORE I9 8VA, RX550 2GB")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Novicompu", "HP", "Intel Core i9 8va",
					"4TB HDD", "16GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "RX550 2GB",
					"Windows 10 Home", "USB3.0 x 6", "3499.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPU HP ORIGINAL CORE I3 8VA, 1TB, 8GB")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Novicompu", "HP", "Intel Core i3 8va",
					"1TB HDD", "8GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 Home", "USB3.0 x 6", "485.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPU LENOVO RYZEN 3 1TB, 8GB")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Novicompu", "Lenovo", "RYZEN 3 2200G 3.5GHZ",
					"1TB HDD", "8GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "AMD RADEON VEGA 8",
					"Windows 10 Home", "USB3.0 x 6", "440.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPU LENOVO AMD A9, 1tb, 4gb")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Novicompu", "Lenovo", "AMD A9",
					"1TB HDD", "4GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "AMD RADEON",
					"Windows 10 Home", "USB3.0 x 6 \n Bluetooth", "275.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPU HP Original Core i3 9na, 1tb")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Novicompu", "HP", "Intel Core i3 9na generacion",
					"1TB HDD + 128GB SSD", "8GB DDR4", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 Home", "USB3.0 x 4", "535.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("All in One HP 24 pulg touch, core i5 8va")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Novicompu", "HP", "Intel Core i5 8na generacion",
					"1TB HDD", "8GB DDR4 + 16GB Optane", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 Home", "USB3.0 x 2", "960.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPU Lenovo Core i5 9na, 1tb")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Novicompu", "Lenovo", "Intel Core i5 9na generacion",
					"256GB SSD", "12GB DDR4 + 16GB Optane", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 Home", "USB3.0 x 2", "677.00"));
		} else if (cmbPrearmadaEscritorio.getSelectedItem().equals("CPU Lenovo Core i5 9na, 1tb")) {
			txaDetallesEscritorio.setText(
				llenarPreArmadas("Novicompu", "Lenovo", "Intel Core i5 9na generacion",
					"256GB SSD", "12GB DDR4 + 16GB Optane", "No Incluye",
					"No Aplica", "No Incluye", "DVD WRITER", "INTEL GRAPHICS",
					"Windows 10 Home", "USB3.0 x 2", "677.00"));
		} else {
			txaDetallesEscritorio.setText("Escoja una computadora");
		}
        }//GEN-LAST:event_cmbPrearmadaEscritorioItemStateChanged

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
	    GestionLogin nuevaVentana = new GestionLogin();
	    nuevaVentana.setVisible(true);
	    this.setVisible(false);
    }//GEN-LAST:event_btnInicioActionPerformed

        private void cbxActivar2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxActivar2ItemStateChanged
		// TODO add your handling code here:
		if (!mostrarAdvertencia(evt)) {
			if (evt.getStateChange() == ItemEvent.SELECTED) {
				rbtnEi7.setEnabled(true);
				rbtnEi5.setEnabled(true);
				rbtnEi3.setEnabled(true);
				panelEProcesador.setEnabled(true);
				rbtnVentilador.setEnabled(true);
				rbtnLiquida.setEnabled(true);
				panelVentilacion.setEnabled(true);
				panelRam.setEnabled(true);
				cmbRam.setEnabled(true);
				panelFuente.setEnabled(true);
				cmbFuente.setEnabled(true);
				panelAlmacenamiento.setEnabled(true);
				rbtnHDD.setEnabled(true);
				rbtnSSD.setEnabled(true);

				panelEProcesador1.setEnabled(true);
				rbtnE7.setEnabled(true);
				rbtnE5.setEnabled(true);
				rbtnE9.setEnabled(true);
			} else if (evt.getStateChange() == ItemEvent.DESELECTED) {
				rbtnEi7.setEnabled(false);
				rbtnEi5.setEnabled(false);
				rbtnEi3.setEnabled(false);
				panelEProcesador.setEnabled(false);
				rbtnVentilador.setEnabled(false);
				rbtnLiquida.setEnabled(false);
				panelVentilacion.setEnabled(false);
				panelRam.setEnabled(false);
				cmbRam.setEnabled(false);
				panelFuente.setEnabled(false);
				cmbFuente.setEnabled(false);
				panelAlmacenamiento.setEnabled(false);
				rbtnHDD.setEnabled(false);
				rbtnSSD.setEnabled(false);
				panelEProcesador1.setEnabled(false);
				rbtnE7.setEnabled(false);
				rbtnE5.setEnabled(false);
				rbtnE9.setEnabled(false);
			}
		}

        }//GEN-LAST:event_cbxActivar2ItemStateChanged

        private void cbxActivar1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxActivar1ItemStateChanged
		// TODO add your handling code here:
		if (evt.getStateChange() == ItemEvent.SELECTED) {
			cmbPrearmadaEscritorio.setEnabled(true);
			panelEPrearmadas.setEnabled(true);
		} else if (evt.getStateChange() == ItemEvent.DESELECTED) {
			cmbPrearmadaEscritorio.setEnabled(false);
			panelEPrearmadas.setEnabled(false);
		}
        }//GEN-LAST:event_cbxActivar1ItemStateChanged

    private void btnECotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnECotizacionActionPerformed
	    if (cmbProvincia.getSelectedIndex() != 0) {
		    String provincia = cmbProvincia.getSelectedItem().toString();
		    boolean RAMSeleccionada = llenarRAM(provincia);
		    boolean almacenamientoSeleccionado = llenarAlmacenamiento(provincia);
		    boolean procesadorSeleccionado = llenarProcesador(provincia);
		    boolean fuenteSeleccionada = llenarFuenteDePoder(provincia);
		    boolean ventilacionSeleccionada = llenarVentilacion(provincia);

		    boolean llenadoExitoso = RAMSeleccionada
			    || almacenamientoSeleccionado || procesadorSeleccionado
			    || fuenteSeleccionada || ventilacionSeleccionada;
		    if (!llenadoExitoso) {
			    String warning = "No se ha seleccionado ningun campo";
			    JOptionPane.showMessageDialog(rootPane, warning, "Advertencia", JOptionPane.WARNING_MESSAGE);
		    } else {
			    GestionPresentacion nuevaVentana = new GestionPresentacion(productosDeseados);
			    nuevaVentana.setVisible(true);
			    this.setVisible(false);
		    }
	    } else {
		    String error = "Seleccione una provincia";
		    JOptionPane.showMessageDialog(rootPane, error, "Provincia no seleccionada", JOptionPane.ERROR_MESSAGE);
	    }
    }//GEN-LAST:event_btnECotizacionActionPerformed

	public boolean mostrarAdvertencia(java.awt.event.ItemEvent evt) {
		boolean esPichincha = cmbProvincia.getSelectedItem().toString().equals("Pichincha");
		boolean esGuayas = cmbProvincia.getSelectedItem().toString().equals("Guayas");
		boolean esAzuay = cmbProvincia.getSelectedItem().toString().equals("Azuay");
		boolean esLoja = cmbProvincia.getSelectedItem().toString().equals("Loja");
		boolean tieneTiendas = esPichincha || esGuayas || esAzuay || esLoja;
		if (!tieneTiendas) {
			String advertencia = "La provincia seleccionada no tiene tiendas de partes"
				+ "\nProvincias con tiendas: Pichincha, Azuay, Guayas, Loja";
			JOptionPane.showMessageDialog(rootPane, advertencia, "Advertencia", JOptionPane.WARNING_MESSAGE);
			return true;
		}
		return false;
	}

	public void desactivarPartes() {
		cbxActivar2.setSelected(false);

		rbtnEi7.setEnabled(false);
		rbtnEi5.setEnabled(false);
		rbtnEi3.setEnabled(false);
		panelEProcesador.setEnabled(false);
		rbtnVentilador.setEnabled(false);
		rbtnLiquida.setEnabled(false);
		panelVentilacion.setEnabled(false);
		panelRam.setEnabled(false);
		cmbRam.setEnabled(false);
		panelFuente.setEnabled(false);
		cmbFuente.setEnabled(false);
		panelAlmacenamiento.setEnabled(false);
		rbtnHDD.setEnabled(false);
		rbtnSSD.setEnabled(false);
		panelEProcesador1.setEnabled(false);
		rbtnE7.setEnabled(false);
		rbtnE5.setEnabled(false);
		rbtnE9.setEnabled(false);
	}

	public boolean llenarRAM(String provincia) {
		if (cmbRam.getSelectedIndex() != 0) {
			String caracteristica = cmbRam.getSelectedItem().toString();
			caracteristica = caracteristica.substring(0, 1);
			productosDeseados.addAll(Tiendas.obtenerProductos(tiendas, provincia, 1, caracteristica, tipoComputador));
			return true;
		} else {
			return false;
		}
	}

	public boolean llenarAlmacenamiento(String provincia) {
		if (rbtnSSD.isSelected()) {
			productosDeseados.addAll(Tiendas.obtenerProductos(tiendas, provincia, 2, "SSD", tipoComputador));
			return true;
		} else if (rbtnHDD.isSelected()) {
			productosDeseados.addAll(Tiendas.obtenerProductos(tiendas, provincia, 2, "HDD", tipoComputador));
			return true;
		} else {
			return false;
		}
	}

	public boolean llenarProcesador(String provincia) {
		if (rbtnEi3.isSelected()) {
			productosDeseados.addAll(Tiendas.obtenerProductos(tiendas, provincia, 3, "i3", tipoComputador));
			return true;
		}
		if (rbtnEi5.isSelected()) {
			productosDeseados.addAll(Tiendas.obtenerProductos(tiendas, provincia, 3, "i5", tipoComputador));
			return true;
		}
		if (rbtnEi7.isSelected()) {
			productosDeseados.addAll(Tiendas.obtenerProductos(tiendas, provincia, 3, "i7", tipoComputador));
			return true;
		}
		if (rbtnE5.isSelected()) {
			productosDeseados.addAll(Tiendas.obtenerProductos(tiendas, provincia, 3, "5", tipoComputador));
			return true;
		}
		if (rbtnE7.isSelected()) {
			productosDeseados.addAll(Tiendas.obtenerProductos(tiendas, provincia, 3, "7", tipoComputador));
			return true;
		}
		if (rbtnE9.isSelected()) {
			productosDeseados.addAll(Tiendas.obtenerProductos(tiendas, provincia, 3, "9", tipoComputador));
			return true;
		}
		return false;
	}

	public boolean llenarFuenteDePoder(String provincia) {
		if (cmbFuente.getSelectedIndex() == 0) {
			return false;
		}
		String fuente = cmbFuente.getSelectedItem().toString();
		productosDeseados.addAll(Tiendas.obtenerProductos(tiendas, provincia, 4, fuente, tipoComputador));
		return true;
	}

	public boolean llenarVentilacion(String provincia) {
		if (rbtnLiquida.isSelected()) {
			productosDeseados.addAll(Tiendas.obtenerProductos(tiendas, provincia, 5, "Liquida", tipoComputador));
			return true;
		}
		if (rbtnVentilador.isSelected()) {
			productosDeseados.addAll(Tiendas.obtenerProductos(tiendas, provincia, 5, "Standard", tipoComputador));
			return true;
		}
		return false;
	}

	/*

	 */
	private String llenarPreArmadas(String tienda, String marca, String procesador,
		String disco, String memoria,
		String webcam, String bateria,
		String pantalla, String unidad,
		String video, String so,
		String puertos, String precio) {
		return "Tienda : " + tienda + "\n"
			+ "\n"
			+ "Marca : " + marca + "\n"
			+ "\n"
			+ "Procesador : " + procesador + "\n"
			+ "\n"
			+ "Disco : " + disco + "\n"
			+ "\n"
			+ "Memoria : " + memoria + "\n"
			+ "\n"
			+ "WebCam : " + webcam + "\n"
			+ "\n"
			+ "Bateria : " + bateria + "\n"
			+ "\n"
			+ "Pantalla : " + pantalla + "\n"
			+ "\n"
			+ "Unidad : " + unidad + "\n"
			+ "\n"
			+ "Video : " + video + "\n"
			+ "\n"
			+ "S.O : " + so + "\n"
			+ "\n"
			+ "Puertos : " + puertos + "\n"
			+ "\n"
			+ "Precio : US$ " + precio + "\n";
	}

	@Override
	public Image getIconImage() {
		Image retValue = Toolkit.getDefaultToolkit().
			getImage(ClassLoader.getSystemResource("resources/icono.png"));

		return retValue;
	}

	/**
	 * @param args the command line arguments
	 */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GestionEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GestionEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GestionEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GestionEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GestionEscritorio().setVisible(true);
//            }
//        });
//    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.ButtonGroup btaCA;
        private javax.swing.ButtonGroup btaDisco;
        private javax.swing.ButtonGroup btaEProcesador;
        private javax.swing.ButtonGroup btaEProcesador1;
        private javax.swing.ButtonGroup btaVentilacion;
        private javax.swing.JButton btnECotizacion;
        private javax.swing.JButton btnInicio;
        private javax.swing.JCheckBox cbxActivar1;
        private javax.swing.JCheckBox cbxActivar2;
        private javax.swing.JComboBox<String> cmbFuente;
        private javax.swing.JComboBox<String> cmbPrearmadaEscritorio;
        private javax.swing.JComboBox<String> cmbProvincia;
        private javax.swing.JComboBox<String> cmbRam;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JPanel panelAlmacenamiento;
        private javax.swing.JPanel panelEPrearmadas;
        private javax.swing.JPanel panelEProcesador;
        private javax.swing.JPanel panelEProcesador1;
        private javax.swing.JPanel panelEProvinciaBuscar;
        private javax.swing.JPanel panelFuente;
        private javax.swing.JPanel panelRam;
        private javax.swing.JPanel panelVentilacion;
        private javax.swing.JRadioButton rbtnE5;
        private javax.swing.JRadioButton rbtnE7;
        private javax.swing.JRadioButton rbtnE9;
        private javax.swing.JRadioButton rbtnEi3;
        private javax.swing.JRadioButton rbtnEi5;
        private javax.swing.JRadioButton rbtnEi7;
        private javax.swing.JRadioButton rbtnHDD;
        private javax.swing.JRadioButton rbtnLiquida;
        private javax.swing.JRadioButton rbtnSSD;
        private javax.swing.JRadioButton rbtnVentilador;
        private javax.swing.JTextArea txaDetallesEscritorio;
        // End of variables declaration//GEN-END:variables
	class FondoPanel extends JPanel {

		private Image imagen;

		@Override
		public void paint(Graphics g) {
			imagen = new ImageIcon(getClass().getResource("/resources/background.jpg")).getImage();
			g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

			setOpaque(false);

			super.paint(g);
		}
	}
}
