/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_poo;

import java.util.ArrayList;

/**
 *
 * @author Cesar J. Santacruz
 */
public class GestionPresentacion extends javax.swing.JFrame {

    ArrayList<Producto> productosDeseados = new ArrayList<>();

    /*
	 * Creates new form GestionPresentacion
     */
    public GestionPresentacion(ArrayList<Producto> productosDeseados) {
        initComponents();
        this.productosDeseados = productosDeseados;
        presentarProductos();
    }

    public void presentarProductos() {
        if (productosDeseados.isEmpty()) {
            txaPresentacion.setText("Lo sentimos. No existen productos con esas caracteristicas");
        } else {
            txaPresentacion.setText("RESULTADOS DE SU BUSQUEDA:\n\n");
            for (Producto productoDeseado : productosDeseados) {
                txaPresentacion.append(productoDeseado.toString());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                txaPresentacion = new javax.swing.JTextArea();
                btnInicio = new javax.swing.JButton();
                lblPartsBits = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jScrollPane1.setEnabled(false);

                txaPresentacion.setEditable(false);
                txaPresentacion.setColumns(20);
                txaPresentacion.setRows(5);
                jScrollPane1.setViewportView(txaPresentacion);

                btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home.png"))); // NOI18N
                btnInicio.setMaximumSize(new java.awt.Dimension(50, 50));
                btnInicio.setMinimumSize(new java.awt.Dimension(50, 50));
                btnInicio.setOpaque(false);
                btnInicio.setPreferredSize(new java.awt.Dimension(50, 50));
                btnInicio.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnInicioActionPerformed(evt);
                        }
                });

                lblPartsBits.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
                lblPartsBits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblPartsBits.setText("PARTS & BITS");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(lblPartsBits, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(116, 116, 116)
                                                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPartsBits))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        GestionLogin nuevaVentana = new GestionLogin();
        nuevaVentana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * @param args the command line arguments
     */
//	public static void main(String args[]) {
//		/* Set the Nimbus look and feel */
//		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//		 */
//		try {
//			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//				if ("Nimbus".equals(info.getName())) {
//					javax.swing.UIManager.setLookAndFeel(info.getClassName());
//					break;
//				}
//			}
//		} catch (ClassNotFoundException ex) {
//			java.util.logging.Logger.getLogger(GestionPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (InstantiationException ex) {
//			java.util.logging.Logger.getLogger(GestionPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (IllegalAccessException ex) {
//			java.util.logging.Logger.getLogger(GestionPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
//			java.util.logging.Logger.getLogger(GestionPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		}
//		//</editor-fold>
//
//		/* Create and display the form */
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new GestionPresentacion().setVisible(true);
//			}
//		});
//	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnInicio;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lblPartsBits;
        private javax.swing.JTextArea txaPresentacion;
        // End of variables declaration//GEN-END:variables
}
